### ISSUE TITLE
class names with dot notation

### ISSUE THREAD

**Issue by rolojf** [monty5811/postcss-elm-tailwind#13]
First of all, thanks for this tool.

Using tailwindcss and recently I am also using the components from tailwind-ui.

To use these components, Tailwind UI depend on some extensions added to the default Tailwind CSS config (like extra spacing values, updated, colors, additional shadows, etc.)

> These extensions will make their way into Tailwind itself in the future but right now you need to install the `@tailwindcss/ui` plugin to add these extensions to your project.
generated

With the plugin, some new classes are generated as the following:
    , col_gap_1\.5
    , col_gap_2\.5
    , col_gap_3\.5
    , focus__neg_translate_x_3\.5
    , focus__neg_translate_y_0\.5
    , focus__neg_translate_y_1\.5
    , focus__translate_x_1\.5
     ...

But instead of being just a dot, in the source file appears like backslash dot.

These classes were taken form the file named TW.elm generated by postcss. 

When I try to import into an elm program, these names are unacceptable to elm.

Maybe it's just a small change to rename the \. with some other character, maybe ~, don't know if it is valid.

Sorry for my english. I hope I was clear enough.

**Comment by monty5811** [comment]
Thanks Rolando - that's super clear! 
I didn't know you could have a `.` in a CSS class name.

I'll push a fix in the next couple of days that lets you use those classes.
