### ISSUE TITLE
Change to `exposing (..)` ?

### ISSUE THREAD

**Issue by yonigibbs** [monty5811/postcss-elm-tailwind#16]
Hi @monty5811. Would it possibly make sense to change the generated code in `TW.elm` to have `exposing (..)` at the top instead of manually including every function in the `exposing` statement? From what I could see all functions are exposed, so it would have no functional impact (though I might well have missed something). And it would reduce the size of the generated file a bit (on my system, with fontawesome classes included, the `exposing` statement is over 14,000 lines long).

**Comment by sparksp** [comment]
I had the same findings with this. Whilst being explicit about the API we're exposing is good in a normal sense, this isn't a typical API. It's unlikely that we'll be concerned about what elm-analyse or elm-review think of these modules either.  Perhaps an option if you'd like to keep explicit exposing yourself for people who don't?

**Comment by monty5811** [comment]
I would rather not add yet another option. And I don't like folk having to add an exclude rule for their tooling when it's easy enough to set it up so they don't have to.

I'd prefer to just leave the list as is.

Happy to be convinced otherwise though.

**Comment by yonigibbs** [comment]
I don't think this is a big deal, so @monty5811 if you prefer the current solution I'm happy to stick with it. I guess `TW.elm` is a file users would not go into very frequently. And as it's tens of thousands of lines long anyway, what's an extra 14,000 between friends 😄 

So yeah, I'm happy to reject this issue if you both are.

**Comment by sparksp** [comment]
The whole file just slows down some of the tools in my chain, it's not the end of the world though, I just have to use them standalone instead of integrated with the IDE, and it's not this project's fault that they can't handle a 75k line file gracefully.

Close away! :)
