### ISSUE TITLE
Small typo in the Readme

### ISSUE THREAD

**Issue by NicolasGuilloux** [monty5811/postcss-elm-tailwind#21]
Hi! :)

Thanks for this library, I'm just getting started with it and it looks very great.

I just noticed that I was having trouble to configure the Elm module name until I found that I wrote `elmModule` instead of `elmModuleName` in the postcss.config.js. It looks like in the ReadMe, there is a small typo in the Usage/With config (https://github.com/monty5811/postcss-elm-tailwind#with-config).

Cheers!

**Comment by monty5811** [comment]
Ah, thanks - will get that sorted 😁
