### ISSUE TITLE
groupFocus and groupHover

### ISSUE THREAD

**Issue by negcx** [monty5811/postcss-elm-tailwind#26]
First, thanks for this great package. Very cool!

When I run the script it seems that it's generating a bunch of invalid Elm functions, not sure what in Tailwind might be causing them:
```

groupFocus DotgroupFocusBgTransparent : Html.Attribute msg
groupFocus DotgroupFocusBgTransparent =
    A.class "group:focus .group-focus:bg-transparent"
```

Do you know why this might be happening?

Thank you!

**Comment by monty5811** [comment]
Hi! Thanks for reaching out 😄 

I've published a new release, that - I think- should fix that...

Can you please upgrade to 0.10.0 and see how you get on?

Thanks!

**Comment by negcx** [comment]
Looks like it worked!

```
focusPlaceholderBlue900Focus : Html.Attribute msg
focusPlaceholderBlue900Focus =
    A.class "focus:placeholder-blue-900:focus"
```

There are some like this that look a bit curious, not sure if those are correct or not?

**Comment by sparksp** [comment]
Are you able to share your Tailwind config with us? Then we can try to generate the same CSS you've got and see if that does make sense. Generally Tailwind generates single selector rules (i.e. no spaces) so I'm interested where your original issue came from - it might highlight a case that we've not catered for.

**Comment by negcx** [comment]
It seems like there are some weird styles in the CSS file:

```
.focus\:placeholder-gray-400:focus::placeholder {
  --placeholder-opacity: 1;
  color: #cbd5e0;
  color: rgba(203, 213, 224, var(--placeholder-opacity));
}
```

My Tailwind config is actually empty, so I think everything's pretty standard:

PostCSS
```
module.exports = {
    plugins: [
        require("tailwindcss"),
        require("postcss-elm-tailwind")({
            elmFile: "src/Tailwind.elm",
            elmModuleName: "Tailwind",
            nameStyle: "camel"
        })
    ]
};
```

tailwind.config.js
```
module.exports = {
  purge: [],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
}

```

package.json
```
{
  "devDependencies": {
    "@tailwindcss/ui": "^0.3.0",
    "postcss": "^7.0.32",
    "postcss-cli": "^7.1.1",
    "postcss-elm-tailwind": "^0.10.0",
    "tailwindcss": "^1.4.6"
  }
}

```

**Comment by sparksp** [comment]
Hmm, that's interesting then, so it looks like that is normal Tailwind. We can see `focus:placeholder-gray-500` in the [tailwind documentation](https://tailwindcss.com/docs/placeholder-color/#focus) but we're also grabbing the `:focus` too. It's the use of colons that confuse things.
