### ISSUE TITLE
Migrate to postcss 8 plugin

### ISSUE THREAD

**Issue by monty5811** [monty5811/postcss-elm-tailwind#31]
Details: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by jangerhard** [comment]
#53 

I created a PR which upgrades to postcss 8.0.0, as well as tailwind 2.0 and the new @tailwindcss/forms. There are some slight pixel-differences, but hopefully nothing too drastic.

**Comment by jangerhard** [comment]
Closed by #53
