### ISSUE TITLE
Invalid Elm code generated when `even` and `odd` variants included

### ISSUE THREAD

**Issue by yonigibbs** [monty5811/postcss-elm-tailwind#7]
Hi. Love the idea of this project. Great work! Really hoping to be able to use it.

Am trying to get it working for the first time and unfortunately seem to have hit an issue. In my `tailwind.config.js` I have this:

```
module.exports = {
    theme: {
        extend: {},
    },
    variants: {
        tableLayout: ['responsive', 'hover', 'focus'],
        backgroundColor: ['responsive', 'first', 'last', 'hover', 'focus', 'even', 'odd']
    },
    plugins: [],
}
```

This caused code such as this to be generated in `TW.elm`:

```
even_bg_transparent_nth_child(even) : Html.Attribute msg
even_bg_transparent_nth_child(even) =
    A.class "even:bg-transparent:nth-child(even)"
```

(Notice the `(even)` in the function name.)

If I remove `odd` and `even` from the variants in `tailwind.config.js` the problem disappears.  Looks like some illegal characters not been replaced maybe?

Is this a bug or am I doing something wrong?

Thanks!

**Comment by monty5811** [comment]
Thanks for reaching out!

You are doing nothing wrong - it is a bug! I'll get it sorted in the next few days.

Thanks again for reporting it!
